version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    container_name: node-container
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    container_name: react-container
    stdin_open: true
    volumes:
       - ./app:/usr/src/app/app
       - /usr/src/app/app/node_modules